//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonNumberMatchingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFile
    {
        public int AppFileID { get; set; }
        public string Title { get; set; }
        public string FileURL { get; set; }
        public string Description { get; set; }
        public int FileType { get; set; }
        public int FileCategory { get; set; }
        public Nullable<bool> IsDownloaded { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
