//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonNumberMatchingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circle
    {
        public int CircleID { get; set; }
        public string CircleName { get; set; }
        public string Code { get; set; }
        public string Category { get; set; }
        public string City { get; set; }
    }
}
