//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonNumberMatchingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadCollection
    {
        public int ID { get; set; }
        public string PhoneNumber { get; set; }
        public string OperatorCode { get; set; }
        public string CircleCode { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
    }
}
