//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonNumberMatchingApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MachingAppEntities : DbContext
    {
        public MachingAppEntities()
            : base("name=MachingAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppFile> AppFile { get; set; }
        public virtual DbSet<UserRegister> UserRegister { get; set; }
        public virtual DbSet<Circle> Circle { get; set; }
        public virtual DbSet<NetworkOperator> NetworkOperator { get; set; }
        public virtual DbSet<LeadCollection> LeadCollection { get; set; }
    }
}
